// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Open(arg1:string):Promise<void>;

export function Query(arg1:string):Promise<Array<main.QueryResult>>;
