// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Body(arg1) {
  return window['go']['main']['App']['Body'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}
